In [1]:
import numpy as np
import h5py
original = h5py.File('/home/desmondhe/Windows_D/ADwithAE/background_for_training.h5', 'r')
ADC_orginal = h5py.File('ADC_Delphes_original_divisions.hdf5', 'r')
ADC_sig = h5py.File('ADC_Delphes_signals.hdf5', 'r')

datasets = np.load('datasets_-1.npz')
background_ID = np.load('background_IDs_-1.npz')

In [2]:
for key in original.keys():
    print(key, original[key].shape)

Particles (13451915, 19, 4)
Particles_Classes (4,)
Particles_Names (4,)


In [19]:
print(np.array(original['Particles_Classes']))
print(np.array(original['Particles_Names']))

[b'MET_class_1' b'Four_Ele_class_2' b'Four_Mu_class_3' b'Ten_Jet_class_4']
[b'Pt' b'Eta' b'Phi' b'Class']


In [3]:
print(ADC_orginal.keys())
print(ADC_sig.keys())

<KeysViewHDF5 ['labels_test', 'labels_train_fold_0', 'labels_train_fold_1', 'labels_train_fold_2', 'labels_train_fold_3', 'labels_train_fold_4', 'x_test', 'x_train_fold_0', 'x_train_fold_1', 'x_train_fold_2', 'x_train_fold_3', 'x_train_fold_4']>
<KeysViewHDF5 ['ato4l', 'ato4l_labels', 'hChToTauNu', 'hChToTauNu_labels', 'hToTauTau', 'hToTauTau_labels', 'leptoquark', 'leptoquark_labels']>


In [4]:
for key in ADC_orginal.keys():
    print(key, ADC_orginal[key].shape)

labels_test (2890383,)
labels_train_fold_0 (2311109,)
labels_train_fold_1 (2312430,)
labels_train_fold_2 (2312798,)
labels_train_fold_3 (2313588,)
labels_train_fold_4 (2311606,)
x_test (2890383, 57)
x_train_fold_0 (2311109, 57)
x_train_fold_1 (2312430, 57)
x_train_fold_2 (2312798, 57)
x_train_fold_3 (2313588, 57)
x_train_fold_4 (2311606, 57)


In [5]:
for key in ADC_sig.keys():
    print(key, ADC_sig[key].shape)

ato4l (55969, 57)
ato4l_labels (55969,)
hChToTauNu (760272, 57)
hChToTauNu_labels (760272,)
hToTauTau (691283, 57)
hToTauTau_labels (691283,)
leptoquark (340544, 57)
leptoquark_labels (340544,)


In [18]:
print(background_ID.keys())
for key in datasets.keys():
    print(key)

KeysView(NpzFile 'background_IDs_-1.npz' with keys: background_ID_train, background_ID_test, background_ID_val, background_ID_names)
x_train
y_train
x_test
y_test
x_val
y_val


In [12]:
for key in background_ID.keys():
    print(key)
    print(background_ID[key].shape)
    print(background_ID[key][:3])

background_ID_train
(8671148,)
[1. 0. 0.]
background_ID_test
(2890383,)
[0. 1. 1.]
background_ID_val
(2890383,)
[0. 0. 2.]
background_ID_names
(4,)
[b'W_0' b'QCD_1' b'Z_2']


In [4]:
for key in datasets.keys():
    print(key, datasets[key].shape)

x_train (8671148, 19, 3, 1)
y_train (8671148, 19, 3, 1)
x_test (2890383, 19, 3, 1)
y_test (2890383, 19, 3, 1)
x_val (2890383, 19, 3, 1)
y_val (2890383, 19, 3, 1)


In [13]:
print(datasets['x_train'][0])

[[[13.65091991]
  [ 0.        ]
  [-1.61326444]]

 [[28.93702888]
  [ 0.81659317]
  [-1.67997897]]

 [[ 0.        ]
  [ 0.        ]
  [ 0.        ]]

 [[ 0.        ]
  [ 0.        ]
  [ 0.        ]]

 [[ 0.        ]
  [ 0.        ]
  [ 0.        ]]

 [[ 0.        ]
  [ 0.        ]
  [ 0.        ]]

 [[ 0.        ]
  [ 0.        ]
  [ 0.        ]]

 [[ 0.        ]
  [ 0.        ]
  [ 0.        ]]

 [[ 0.        ]
  [ 0.        ]
  [ 0.        ]]

 [[45.79579163]
  [ 0.89488125]
  [-1.72020626]]

 [[44.72616959]
  [ 2.7366116 ]
  [ 1.03738618]]

 [[36.32344055]
  [-0.62255085]
  [ 2.19731951]]

 [[ 0.        ]
  [ 0.        ]
  [ 0.        ]]

 [[ 0.        ]
  [ 0.        ]
  [ 0.        ]]

 [[ 0.        ]
  [ 0.        ]
  [ 0.        ]]

 [[ 0.        ]
  [ 0.        ]
  [ 0.        ]]

 [[ 0.        ]
  [ 0.        ]
  [ 0.        ]]

 [[ 0.        ]
  [ 0.        ]
  [ 0.        ]]

 [[ 0.        ]
  [ 0.        ]
  [ 0.        ]]]


In [7]:
background_ID['background_ID_names']

array([b'W_0', b'QCD_1', b'Z_2', b'tt_3'], dtype='|S5')

In [6]:
for key in background_ID.keys():
    print(key, background_ID[key].shape)

background_ID_train (8671148,)
background_ID_test (2890383,)
background_ID_val (2890383,)
background_ID_names (4,)


In [11]:
print(np.unique(background_ID['background_ID_train']))
print(np.unique(background_ID['background_ID_test']))
print(np.unique(background_ID['background_ID_val']))

[0. 1. 2. 3.]
[0. 1. 2. 3.]
[0. 1. 2. 3.]


In [160]:
unpreprocessed_labels = ['x_train','x_test', 'x_val']
full_SM_dataset = np.concatenate([datasets[label] for label in unpreprocessed_labels], axis=0)
bkg = full_SM_dataset.reshape(full_SM_dataset.shape[:3])
ID_names = ['W', 'QCD', 'Z', 'ttbar']

In [4]:
set_labels = ['background_ID_train', 'background_ID_test', 'background_ID_val']
bkg_labels = np.concatenate([background_ID[label] for label in set_labels], axis=0)

In [83]:
random_index = np.random.randint(len(bkg))
print(random_index, ID_names[int(bkg_labels[random_index])])
print(bkg[random_index])

13918915 W
[[52.48708344  0.          1.65952969]
 [26.64757729 -1.50787604 -1.13222659]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]


In [108]:
train = datasets['x_train']
train_y = datasets['y_train']
train_ID = background_ID['background_ID_train']

In [158]:
print(np.where(train_ID == 3))

(array([    130,     358,     614, ..., 8669834, 8670634, 8670726]),)


In [170]:
random_index = np.random.randint(len(train))
print(random_index)
print(ID_names[int(train_ID[random_index])])
print(train[random_index].reshape(19,3))

671720
QCD
[[ 5.10717821  0.         -0.8216452 ]
 [31.53635406 -0.84333408  1.28201449]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [56.95665741 -1.47270215 -1.59351039]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]


In [121]:
print(train_y[random_index].reshape(19,3))

[[ 1.53438832  0.          0.68720973]
 [ 0.65128832  2.54779649 -2.72856641]
 [-0.          0.          0.        ]
 [-0.          0.          0.        ]
 [-0.          0.          0.        ]
 [-0.          0.          0.        ]
 [-0.          0.          0.        ]
 [-0.          0.          0.        ]
 [-0.          0.          0.        ]
 [-0.4401405  -0.01823246  0.84574872]
 [-0.          0.          0.        ]
 [-0.          0.          0.        ]
 [-0.          0.          0.        ]
 [-0.          0.          0.        ]
 [-0.          0.          0.        ]
 [-0.          0.          0.        ]
 [-0.          0.          0.        ]
 [-0.          0.          0.        ]
 [-0.          0.          0.        ]]


In [173]:
random_index = 614
print(random_index)
print(ID_names[int(train_ID[random_index])])
print(train[random_index].reshape(19,3))

614
ttbar
[[ 5.37197151e+01  0.00000000e+00  4.57214355e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.38952438e+02  4.34099622e-02 -4.48926181e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.18071152e+02 -8.14922214e-01  2.16640520e+00]
 [ 5.83801804e+01 -1.61392665e+00  2.43012667e+00]
 [ 5.00954361e+01 -5.11343956e-01 -1.68490660e+00]
 [ 2.09486179e+01  1.63368797e+00 -2.12641406e+00]
 [ 2.05003662e+01  1.68510187e+00 -1.19171000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]
